dev:
  PORT: 80
  MONGO_HOST:  "mongodb+srv://####:####@cluster0.ws7xq.gcp.mongodb.net/test?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary&ssl=true"
  MONGO_DB: "starwars_qa"

qa:
  MONGO_HOST:  "mongodb+srv://####:####@cluster0.ws7xq.gcp.mongodb.net/test?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary&ssl=true"
  MONGO_DB: "starwars_qa"

prod:
  MONGO_HOST: "mongodb+srv://####:####@cluster0.ws7xq.gcp.mongodb.net/test?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary&ssl=true"
  MONGO_DB: "starwars_prod"
